### ISSUE TITLE
context.isAuthenticated() is not working on the client side.

### ISSUE THREAD

**Issue by jimmy-e** [jkettmann/graphql-passport#24]
**Problem:**
`context.isAuthenticated()` is not working on the client side. When I login using the playground and then test `isAuthenticated()`, I get back true, however, when I try to reproduce this on the client side using react and apollo client, I get back false.

**To Reproduce:**
*for the backend:*
1. [Clone this repo/branch](https://github.com/jimmy-e/mybord-server/tree/passport_testing_v3)
2. Run `yarn`
3. Run `yarn build:dev`
4. In a second terminal, run `yarn run:dev`.
5. Login using the playground.
```
mutation {
  login(email: "j@gmail.com", password: "abc") {
    user {
      id
      firstName
      lastName
      email
    }
  }
}
```
6. Run the `isAuthenticated` query. You should get the response of `true`.
```
query {
  isAuthenticated
}
```

*for the frontend:*
1. [Clone this repo/branch](https://github.com/jimmy-e/mybord/tree/testing_passport)
2. Run `yarn`
3. Run `yarn build:dev`
4. Run `yarn start`
5. The browser should open to `localhost:8080`. Use the same credentials as before to login. Note in the dev console that the result of `isAuthentication` query is `false`. The code for this form can be found [here](https://github.com/jimmy-e/mybord/blob/testing_passport/src/forms/loginForm/loginForm.tsx), or seen below:

```js
import * as React from 'react';
import gql from 'graphql-tag';
import { Form } from 'antd';
import { useLazyQuery, useMutation } from '@apollo/react-hooks';
import { FormProp } from 'types/formTypes';
import FormItem from '../formItem/formItem';
import Button from '../../buttons/button/button';
import PasswordInput from '../../inputs/passwordInput/passwordInput';
import TextInput from '../../inputs/textInput/textInput';
import * as styles from './loginForm.module.less';
import './loginForm.less';

const IS_AUTHENTICATED = gql`
  query isAuthenticated {
    isAuthenticated
  }
`;

const LOGIN = gql`
  mutation login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
      user {
        id
        firstName
      }
    }
  }
`;

interface Props {
  form: FormProp;
}

const LoginForm: React.FC<Props> = ({ form }) => {
  const [isAuthenticated, { called, data, loading }] = useLazyQuery(IS_AUTHENTICATED);
  const [loginUser] = useMutation(LOGIN);

  // @ts-ignore // ToDo: remove ts ignore
  const handleLogin = async (): void => {
    const values = form.getFieldsValue();
    try {
      await loginUser({
        variables: {
          email: values.email,
          password: values.password,
        },
      });
      isAuthenticated();
    } catch (error) {
      console.log(error);
    }
  };

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>): void => {
    event.preventDefault();
    form.validateFields((error) => {
      if (!error) {
        handleLogin();
      }
    });
  };

  if (called && !loading) {
    console.log('@@@@@@@@@@@@@@@@@');
    console.log(data);
  }

  return (
    <Form
      className={styles.form}
      onSubmit={handleSubmit}
    >
      <FormItem
        fieldName="email"
        form={form}
      >
        <TextInput placeholder="Email" />
      </FormItem>
      <FormItem
        fieldName="password"
        form={form}
      >
        <PasswordInput placeholder="Password" />
      </FormItem>
      <FormItem
        fieldName="login"
        form={form}
      >
        <Button
          htmlType="submit"
          label="Login"
          onClick={handleLogin}
        />
      </FormItem>
    </Form>
  );
};

export default Form.create()(LoginForm);
```

**Comment by gforge** [comment]
A quick look hints that:

```
    isAuthenticated: (parent, args, context) => context.passport.isAuthenticated(),
```

Should be:

```
    isAuthenticated: (parent, args, context) => context.isAuthenticated(),
```

**Comment by jimmy-e** [comment]
Thanks @gforge but my server actually looks like [this](https://github.com/jimmy-e/mybord-server/blob/passport_testing_v3/src/index.ts#L50):

```
const server = new ApolloServer({
  context: (request) => ({
    passport: buildContext({ req: request.req, res: request.res, Users }),
    pubsub,
  }),
  resolvers,
  typeDefs,
  playground: {
    settings: {
      'request.credentials': 'same-origin',
    },
  },
  subscriptions: {
    onConnect: createOnConnect([
      sessionMiddleware,
      passportMiddleware,
      passportSessionMiddleware,
    ]),
  },
});
```

**Comment by gforge** [comment]
In what way does this populate context.passport in the resolver?

**Comment by jimmy-e** [comment]
ApolloServer's context can be used as an object, so I'm just assigning `graphql-passport`'s `buildContext` to the named `passport` object. In addition, this is fully functional on the playground. The issue is that, for some reason, is not returning the expected values on the client side of my react application.

**Comment by jkettmann** [comment]
I didn't have time yet to have a more detailed look at your repositories. But if it works in the playground and not with the apollo client there is probably something wrong with the setup and not with the server itself or this library.

The first thing you can try to debug the problem is to check if the cookie is set after login. This is a common error. If it's not set `isAuthenticated` will never be true.

**Comment by jimmy-e** [comment]
Thanks @jkettmann , I haven't set up any cookies, so that is probably the problem. Do you have any examples or resources to point to on how to do this? Still learning this. Thanks!

**Comment by jkettmann** [comment]
You already set up your cookies by using [express-session here](https://github.com/jimmy-e/mybord-server/blob/passport_testing_v3/src/index.ts#L38) ;-)

What I mean is: Navigate to your app in a browser (I'm assuming Chrome) and open the developer tools. Then open the `Application` tab. In the left menu click on Storage -> Cookies. If there are any delete them. 

Now execute the login from the app. If everything is set up correctly you should see a new cookie with something like `session` in its name.

**Comment by jimmy-e** [comment]
Hi @jkettmann , thanks for the response, and sorry for the delay.

I deleted all cookies via dev console in Chrome and tried logging in again and got the same results (console log message of `{isAuthenticated: false}`). I also don't see any new cookies, just the standard NID cookie. This also happens when I use incognito mode.

**Comment by jimmy-e** [comment]
Hi @jkettmann , was wondering if you have any updates. Here is what I have after a little more debugging:

- If I go to my local graphql playground, `http://localhost:4000/graphql`, and run the `login` mutation, a cookie called `connect.sid` is set. I am then successfully able to run the `isAuthenticated` query and am returned true.
- If I first go to my local graphql playground and run the `login` mutation, a cookie called `connect.sid` is set. I then go to my local client, `http://localhost:8080/`, and of course the `connect.sid` cookie is still present. However, when I try to login and the `isAuthenticated` query gets run by the client, I am returned false.
- If I clear my cookies and go first to my local client and run the login mutation via the ux, no cookie is sent.

**Comment by ShehabSN** [comment]
Hi @jimmy-e I had a similar issue as you in terms of cookies, how you can ensure that the client side is capable of receiving and using the cookie from your backend you need some configuration with cors since you are using different domains for backend/frontend

Make sure you have this in your backend:
`var corsOptions = {
  origin:"http://localhost:3000",
  credentials: true,
};
app.use(cors(corsOptions));`

also make sure you either set cors to be false or directly pass in your corsOptions, it seems since Apollo by default sets cors access  control allow origin to be *, this doesnt allow your frontend to receive the cookie so
`server.applyMiddleware({ app, path: '/graphql' ,cors:false});`

Then on your frontend you need this
`const client = new ApolloClient({
	cache: new InMemoryCache(),
	link: new HttpLink({
		credentials: 'include',
		uri: 'http://localhost:8000/graphql',
	}),
});`
Try it out and see

**Comment by jkettmann** [comment]
Thanks @ShehabSN for helping out. If this doesn't work let me know. Then I'll have a closer look in the next days

**Comment by jimmy-e** [comment]
Hi @ShehabSN and @jkettmann , thank you @ShehabSN for the reply and apologies for the delay!

I made the updates per @ShehabSN in the [backend branch](https://github.com/jimmy-e/mybord-server/tree/passport_testing_v3) (see [this commit](https://github.com/jimmy-e/mybord-server/commit/e846cb7ceecbb3b2e0ae2feabb8973fb671e61f7)) and the [frontend branch](https://github.com/jimmy-e/mybord/tree/testing_passport)(see [this commit](https://github.com/jimmy-e/mybord/commit/518c99ec118c979929a0c2e6a5c8e244983e58d5)).

However, when I now try to 'login' / have my front end make a the graphql login mutation, I get this console message:

> Error: Network error: Failed to fetch
    at new ApolloError (bundle.esm.js:63)
    at Object.error (bundle.esm.js:1030)
    at notifySubscription (Observable.js:140)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.error (Observable.js:240)
    at bundle.esm.js:869
    at Set.forEach (<anonymous>)
    at Object.error (bundle.esm.js:869)
    at notifySubscription (Observable.js:140)
    at onNotify (Observable.js:179)

**Comment by jimmy-e** [comment]
Hi @ShehabSN @jkettmann , is there any update for this?

**Comment by jkettmann** [comment]
Oh sorry, forgot about this. I'll have a look tomorrow

**Comment by jimmy-e** [comment]
Thanks @jkettmann, hope you're doing well.

**Comment by jkettmann** [comment]
The answer of @ShehabSN was almost correct. Only the cors domain is not localhost:3000. I also pulled the cors middleware up so it's the first middleware used. Not sure if that made a difference though. You'd need to check.

This should fix your problem.

```
const PORT = 4000;
const APP_PORT = 8080;

// Adds express as middleware to our server.
const app = express();
app.use(cors({ origin: `http://localhost:${APP_PORT}`, credentials: true }));
app.use(sessionMiddleware);
app.use(passportMiddleware);
app.use(passportSessionMiddleware);
```

**Comment by jimmy-e** [comment]
Thank you @jkettmann and @ShehabSN for all the help;

The other issue was that the apollo client should have its uri set to the graphql PORT (in this case 4000, and not 8000).

`const client = new ApolloClient({ cache: new InMemoryCache(), link: new HttpLink({ credentials: 'include', uri: 'http://localhost:4000/graphql', }), });`
