### ISSUE TITLE
context.passport.getUser() is not working on the client side

### ISSUE THREAD

**Issue by jimmy-e** [jkettmann/graphql-passport#32]
**Problem:**
`context.passport.getUser()` is not working on the client side. When I login using the playground and then run the `currentUser` query, I am returned the expected results, however, when I try to reproduce this on the client side using react and apollo client, I get back undefined.

Note, [my previous ticket](https://github.com/jkettmann/graphql-passport/issues/24) had similar issues with getting `context.passport.isAuthenticated` to work client side. Not sure why this is working now but `context.passport.getUser` isn't working.

**To Reproduce:**
*for the backend:*
1. [Clone this repo/branch](https://github.com/jimmy-e/mybord-server/tree/context_user_bug)
2. Run `yarn`
3. Run `yarn build:dev`
4. In a second terminal, run `yarn run:dev`.
5. Login using the playground.
```
mutation {
  login(email: "j@gmail.com", password: "abc") {
    user {
      id
      firstName
      lastName
      email
    }
  }
}
```

6. Run the `isAuthenticated` query. You should get the response of `true`.
```
query {
  isAuthenticated
}
```

7. Run the `currentUser` query. You should get back an accurate response.
```
query{
  currentUser{
    email
    firstName
    lastName
  }
}
```

*for the frontend:*
1. [Clone this repo/branch](https://github.com/jimmy-e/mybord/tree/context_user_bug)
2. Run `yarn`
3. Run `yarn build:dev`
4. Run `yarn start`
5. The browser should open to `localhost:8080`.
6. Click the 'login' button, which will login using the same credentials as the playground.
7. Click the 'isAuthenticated' button, which will confirm that you are authenticated.
8. (make sure you have the dev console open) Click the 'Current User' button, which will perform the current user query. You will see in the console that undefined results are returned.

**Comment by jimmy-e** [comment]
hey @jkettmann I'm sure you're busy but let me know if you have a chance to look into this, thanks!

**Comment by jkettmann** [comment]
Hey Jimmy. Sorry for missing this. Still don't get notifications somehow. I'll try to have a look tomorrow. Thanks for providing an example repo btw

**Comment by jkettmann** [comment]
I tried to run the server but it gives an error because of a missing `dev.env` file. What do I need to add to that file?

**Comment by jkettmann** [comment]
@jimmy-e in case you also don't receive notifications :smile:

**Comment by jimmy-e** [comment]
Thanks @jkettmann , apologies for the delay. I fixed the issue, you should be able to use the same back end branch now if you pull from git.

**Comment by jkettmann** [comment]
I don't think this has anything to do with this library. The query seems to be invalid. This is what I see when clicking the buttons from left to right in the network tab. See the last request? The API returns an error because the field `user` is not defined on the server

![image](https://user-images.githubusercontent.com/9722792/82812072-75621f00-9e92-11ea-88fb-5b10fb141339.png)

**Comment by jimmy-e** [comment]
Apologies @jkettmann , don't know where I tripped up on this, but it is working. Thanks for giving this a look though! Hope you had a good weekend.

**Comment by jkettmann** [comment]
No worries :smile:

**Comment by jimmy-e** [comment]
@jkettmann , posting to this issue / re-opening it up instead of opening a new issue.

You can follow the original instructions but instead use [this front end brach](https://github.com/jimmy-e/mybord/tree/context_user_bug_v3) and [this backend branch](https://github.com/jimmy-e/mybord-server/tree/context_user_bug_v3).

I realized now my issue was when I was trying to use axios to communicate to the backend. I am doing this so I can use [React Suspense](https://reactjs.org/docs/concurrent-mode-suspense.html). However, axios is not getting the authenticated results as anticipated, which you can replicate by clicking the buttons 1, 2 and 3 in order. I am assuming I need to set the headers in my axios request, but am unsure how & to what? Thanks!

**api.ts:**
```js
import axios from 'axios';

const get = async (gqlString: any): Promise<any> => {
  const body = JSON.stringify({ query: gqlString.loc.source.body });
  const config = {
    headers: { 'Content-Type': 'application/json' },
  };
  const response = await axios.post(`http://${process.env.URI}`, body, config);
  return response.data;
};

export default {
  get,
};
```

**Comment by jkettmann** [comment]
If I understand correctly this is working when the requests are sent via GraphQL but not via axios, right? My approach would be to have a look at the headers that are sent with Apollo in the chrome dev tools and try out what you have to set with axios one by one.

Just as a note: Why do you have to use axios to run a GraphQL query? Will you parse the response manually? If so I probably wouldn't go down this road if it's not really necessary.

**Comment by jimmy-e** [comment]
I just needed to add `withCredentials: true` to my axios options 🤦‍♂️
apologies, should have probably posted this to stackoverflow instead.

BTW, need to do this for React Suspense. It's currently in beta but is pretty cool and would recommend [checking it out](https://www.youtube.com/watch?v=8_ZjNnUqarg) if you're curious.

```js
import axios from 'axios';

const get = async (gqlString: any): Promise<any> => {
  const body = JSON.stringify({ query: gqlString.loc.source.body });
  const config = {
    headers: { 'Content-Type': 'application/json' },
    withCredentials: true, // THIS FIXED IT
  };
  const response = await axios.post(`http://${process.env.URI}`, body, config);
  return response.data;
};

export default {
  get,
};
```
