### ISSUE TITLE
Question about context

### ISSUE THREAD

**Issue by gabrielmicko** [jkettmann/graphql-passport#5]
Hey @jkettmann  and contributors, nice work. I really like it. I have a question before I give it a try.
When a successful login happens will this create a cookie or a token? How does it know in other mutations / queries a user is logged in?
Will I have to call `context.isAuthenticated()` in every mutation? If so how does isAuthenticated know that my user is logged in? Will it work with subscriptions too?

**Comment by jkettmann** [comment]
Hi @gabrielmicko!

Actually, this package won't do anything on its own. You will need to use it in combination with [Passport.js](https://github.com/jaredhanson/passport). 

Passport itself also doesn't create a cookie or token. You can use it together with express-session as in [my tutorial about Authentication with GraphQL and Passport](https://jkettmann.com/authentication-and-authorization-with-graphql-and-passport/). In this case, a session ID is saved to a cookie. 

If you want to use JWT you can have a look at [passport-jwt](https://github.com/mikenicholson/passport-jwt). If you get your JWT from some external place like a separate authentication API you don't need to use the `GraphQLLocalStrategy` provided by this package. You could still use the `buildContext` to access the user via `context.user`. But you could copy the request object to the context as well and use `context.req.user` instead. 

About `context.isAuthenticated()`: Where you want to call `context.isAuthenticated` depends on your approach to authorization. You can check if a user has access to a field or mutation in the resolver, that's right. This is probably the most flexible approach. Here is a [list of different possibilities](https://www.apollographql.com/docs/apollo-server/security/authentication/). You can also use a custom directive, a package like graphql-shield or lock down your schema completely when a user is not logged in.

`isAuthenticated` checks if Passport found a user or not. It again depends on the Strategy you use. But basically, it checks if a user object is inside the request or not I guess. I would recommend reading a bit more about Passport.js.

If it's working with subscriptions? Good question, I'm actually not sure. I will try it out when I have some time :-)

**Comment by gabrielmicko** [comment]
Thanks for the information. I tested subscriptions and it does not work. `getUser` returns undefined in subscription resolver.
I am currently trying to bake some code to 
```
  subscriptions: {
    onConnect: async (connectionParams, webSocket, context) => {....
```

to make it work.  This link is somewhat helpful, but does not leverage your buildContext API.

**Comment by jkettmann** [comment]
Thanks for the investigation. Could you by any chance provide an example repo with subscriptions and graphql-passport? I could have a closer look then

**Comment by gabrielmicko** [comment]
My repo's logic is very much the same as your example: https://github.com/jkettmann/authentication-with-graphql-passport-and-react/blob/master/api/index.js

If you add 1 subscription you will see that within onConnect you can get the passport user, but in the context (in the resolver) although the createContext functions are present, but they are not working since req is undefined. :(

**Comment by gabrielmicko** [comment]
Main problem I have is that `isUnauthenticated` and other methods that rely on `request` are not available in websocket. I rewrote the lib so I can better debug:
```
const AuthHandler = ({ connection, request, response }) => {
  const isAuthenticated = () => request.isAuthenticated();
  const isUnauthenticated = () => request.isUnauthenticated();
  const getUser = () => {
    let user = request ? request.user : null;
    if (connection) {
      if (connection.context.user) user = connection.context.user;
    }
    return user;
  };
  const getRequest = () => request;
  const getResponse = () => response;
  const getConnection = () => connection;

  const authenticate = (username, password) =>
    new Promise((resolve, reject) => {
      passport.authenticate('local', (err, user, info) => {
        if (err) reject(err);
        else resolve({ user, info });
      })({ query: { username, password } });
    });

  const login = user =>
    new Promise((resolve, reject) => {
      request.login(user, options, err => {
        if (err) reject(err);
        else resolve();
      });
    });

  const logout = () =>
    new Promise(resolve => {
      request.logout();
      request.session.destroy();
      resolve();
    });

  return {
    getUser,
    getRequest,
    isAuthenticated,
    isUnauthenticated,
    getResponse,
    getConnection,
    authenticate,
    login,
    logout
  };
};

```

Subscription resolver:
```
onConnect: async (connectionParams, webSocket) => {
      const promise = new Promise((resolve, reject) => {
        mySess(webSocket.upgradeReq, {}, () => {
          const sessionPP = webSocket.upgradeReq.session.passport;
          if (sessionPP && sessionPP.user) {
            const users = User.getUsers();
            const matchingUser = users.find(user => user.id === sessionPP.user);
            resolve({ user: matchingUser });
          } else {
            reject();
          }
        });
      });
      const user = await promise;

      return user;
    }
```

Let's say the user is logged in. Subscribe to an endpoint. Logs out. Subscription is still active and receives messages. Of course it doesn't work anymore when user refreshes the page, but that's not good. I need instant cut off for security.

**Comment by gabrielmicko** [comment]
After two nights digging into this I finally found a workaround.

```
import getMemoryStore from 'memorystore';

const MemoryStore = getMemoryStore(session);
const memoryStoreInstance = new MemoryStore({
  checkPeriod: 86400000
});

const mySess = session({
  genid: req => uuid(),
  secret: SESSION_SECRECT,
  resave: false,
  saveUninitialized: false,
  store: memoryStoreInstance
});


 const isAuthenticated = () => {
    return new Promise(resolve => {
      if (request) {
        resolve(request.isAuthenticated());
      } else {
        const sessionID = connection.context.sessionID;
        memoryStoreInstance.get(sessionID, (error, id) => {
          resolve(!error && id != null);
        });
      }
    });
  };
```

**Comment by jkettmann** [comment]
Thanks for the proposal! Unfortunately, I'm quite busy the next days. But I'll try to integrate this in some way as soon as possible.

**Comment by jkettmann** [comment]
@gabrielmicko I finally found some time to have a look at this issue. I found a way to make all the functions available for subscriptions as well. We can make use of Apollo server's `subscriptions.onConnect` option. The link to the issue you provided was very helpful.

The usage looks like this 

```js
import express from 'express';
import session from 'express-session';
import { ApolloServer } from 'apollo-server-express';
import passport from 'passport';
import { GraphQLLocalStrategy, buildContext } from 'graphql-passport';

...
const sessionMiddleware = session(options); // optional
const passportMiddleware = passport.initialize();
const passportSessionMiddleware = passport.session(); // if session is used

const app = express();
app.use(sessionMiddleware);
app.use(passportMiddleware);
app.use(passportSessionMiddleware);

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ req, res }) => buildContext({ req, res, User }),
  subscriptions: {
    onConnect: createOnConnect([
      sessionMiddleware,
      passportMiddleware,
      passportSessionMiddleware,
    ])
  }
});
```

And inside the subscription resolvers you can access the user and so on like following

```js
const resolvers = {
  Subscription: {
    messageReceived: {
      subscribe: withFilter(
        (parent, args, context) => {
          if (context.isUnauthenticated()) {
            throw new Error('You need to be logged in');
          }
          return pubSub.asyncIterator([MESSAGE_RECEIVED])
        },
        (payload, variables, context) => payload.messageReceived.receiverId === context.user.id,
      ),
    },
  },
  Query: { ... },
  Mutation: {
    ...
    sendMessage: (parent, { text, receiverId }, context) => {
      const message = { text, receiverId };
      pubSub.publish(MESSAGE_RECEIVED, { messageReceived: message });
      return message;
    }
  },
};
```

Does this make sense to you? 

Feel free to have a look at the PR #10 and see if it works for you. I'll merge and publish this the next days
