### ISSUE TITLE
Outdated for passport 0.6.0

### ISSUE THREAD

**Issue by ecker00** [jkettmann/graphql-passport#71]
The new 0.6.0 version of passport, changes some of the parameters of login()/logout(), so seems like some changes are needed for `graphql-passport` to be fully compatible.

Example: https://github.com/jaredhanson/passport/commit/17111d76972462eab90a1ea5dcd9211ceb93c7b0
And: https://github.com/jaredhanson/passport/commit/e69834e070662e8972e9eca07cbebf0338cfd226

**Comment by lensbart** [comment]
@jkettmann any chance you could merge https://github.com/jkettmann/graphql-passport/pull/72? Thanks!
